export const healthLabels = () => [
    { label: 'Alcohol-Cocktail', value: 'alcohol-cocktail' },
    { label: 'Alcohol-Free', value: 'alcohol-free' },
    { label: 'Celery-Free', value: 'celery-free' },
    { label: 'Crustcean-Free', value: 'crustacean-free' },
    { label: 'Dairy-Free', value: 'dairy-free' },
    { label: 'DASH', value: 'DASH' },
    { label: 'Egg-Free', value: 'egg-free' },
    { label: 'Fish-Free', value: 'fish-free' },
    { label: 'FODMAP-Free', value: 'fodmap-free' },
    { label: 'Gluten-Free', value: 'gluten-free' },
    { label: 'Immuno-Supportive', value: 'immuno-supportive' },
    { label: 'Keto-Friendly', value: 'keto-friendly' },
    { label: 'Kidney-Friendly', value: 'kidney-friendly' },
    { label: 'Kosher', value: 'kosher' },
    { label: 'Low Potassium', value: 'low-potassium' },
    { label: 'Low Sugar', value: 'low-sugar' },
    { label: 'Lupine-Free', value: 'lupine-free' },
    { label: 'Mediterranean', value: 'Mediterranean' },
    { label: 'Mollusk-Free', value: 'mollusk-free' },
    { label: 'Mustard-Free', value: 'mustard-free' },
    { label: 'No oil added', value: 'no-oil-added' },
    { label: 'Paleo', value: 'paleo' },
    { label: 'Peanut-Free', value: 'peanut-free' },
    { label: 'Pescatarian', value: 'pescatarian' },
    { label: 'Pork-Free', value: 'pork-free' },
    { label: 'Red-Meat-Free', value: 'red-meat-free' },
    { label: 'Sesame-Free', value: 'sesame-free' },
    { label: 'Shellfish-Free', value: 'shellfish-free' },
    { label: 'Soy-Free', value: 'soy-free' },
    { label: 'Sugar-Conscious', value: 'sugar-conscious' },
    { label: 'Sulfite-Free', value: 'sulfite-free' },
    { label: 'Tree-Nut-Free', value: 'tree-nut-free' },
    { label: 'Vegan', value: 'vegan' },
    { label: 'Vegetarian', value: 'vegetarian' },
    { label: 'Wheat-Free', value: 'wheat-free' },
];
